<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from adyen/xml/schema/CRM/Adyen/AdyenNotification.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:ca1ddd08225479ac16eef6d72c984bd7)
 */
use CRM_Adyen_ExtensionUtil as E;

/**
 * Database access object for the AdyenNotification entity.
 */
class CRM_Adyen_DAO_AdyenNotification extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_adyen_notification';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique AdyenNotification ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * ID of event code
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $event_code_id;

  /**
   * Date of the event
   *
   * @var string
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $event_date;

  /**
   * PSP Reference
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $psp_reference;

  /**
   * Merchant Account
   *
   * @var string
   *   (SQL type: varchar(80))
   *   Note that values will be retrieved from the database as a string.
   */
  public $merchant_account;

  /**
   * Processing Order
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $processing_order;

  /**
   * ID of notification status
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $status_id;

  /**
   * Adyen NotificationRequestItem (JSON)
   *
   * @var string
   *   (SQL type: longtext)
   *   Note that values will be retrieved from the database as a string.
   */
  public $notification;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_adyen_notification';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Adyen Notifications') : E::ts('Adyen Notification');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('AdyenNotification ID'),
          'description' => E::ts('Unique AdyenNotification ID'),
          'required' => TRUE,
          'where' => 'civicrm_adyen_notification.id',
          'table_name' => 'civicrm_adyen_notification',
          'entity' => 'AdyenNotification',
          'bao' => 'CRM_Adyen_DAO_AdyenNotification',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'event_code_id' => [
          'name' => 'event_code_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Event Code'),
          'description' => E::ts('ID of event code'),
          'required' => TRUE,
          'where' => 'civicrm_adyen_notification.event_code_id',
          'table_name' => 'civicrm_adyen_notification',
          'entity' => 'AdyenNotification',
          'bao' => 'CRM_Adyen_DAO_AdyenNotification',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'adyen_notification_event_code',
            'optionEditPath' => 'civicrm/admin/options/adyen_notification_event_code',
          ],
          'add' => NULL,
        ],
        'event_date' => [
          'name' => 'event_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Event Date'),
          'description' => E::ts('Date of the event'),
          'required' => TRUE,
          'where' => 'civicrm_adyen_notification.event_date',
          'table_name' => 'civicrm_adyen_notification',
          'entity' => 'AdyenNotification',
          'bao' => 'CRM_Adyen_DAO_AdyenNotification',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
          ],
          'add' => NULL,
        ],
        'psp_reference' => [
          'name' => 'psp_reference',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('PSP Reference'),
          'description' => E::ts('PSP Reference'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_adyen_notification.psp_reference',
          'table_name' => 'civicrm_adyen_notification',
          'entity' => 'AdyenNotification',
          'bao' => 'CRM_Adyen_DAO_AdyenNotification',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'merchant_account' => [
          'name' => 'merchant_account',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Merchant Account'),
          'description' => E::ts('Merchant Account'),
          'required' => TRUE,
          'maxlength' => 80,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_adyen_notification.merchant_account',
          'table_name' => 'civicrm_adyen_notification',
          'entity' => 'AdyenNotification',
          'bao' => 'CRM_Adyen_DAO_AdyenNotification',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'processing_order' => [
          'name' => 'processing_order',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Processing Order'),
          'description' => E::ts('Processing Order'),
          'required' => FALSE,
          'where' => 'civicrm_adyen_notification.processing_order',
          'table_name' => 'civicrm_adyen_notification',
          'entity' => 'AdyenNotification',
          'bao' => 'CRM_Adyen_DAO_AdyenNotification',
          'localizable' => 0,
          'add' => NULL,
        ],
        'status_id' => [
          'name' => 'status_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Notification Status'),
          'description' => E::ts('ID of notification status'),
          'required' => TRUE,
          'where' => 'civicrm_adyen_notification.status_id',
          'default' => '1',
          'table_name' => 'civicrm_adyen_notification',
          'entity' => 'AdyenNotification',
          'bao' => 'CRM_Adyen_DAO_AdyenNotification',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'adyen_notification_status',
            'optionEditPath' => 'civicrm/admin/options/adyen_notification_status',
          ],
          'add' => NULL,
        ],
        'notification' => [
          'name' => 'notification',
          'type' => CRM_Utils_Type::T_LONGTEXT,
          'title' => E::ts('Notification'),
          'description' => E::ts('Adyen NotificationRequestItem (JSON)'),
          'required' => TRUE,
          'where' => 'civicrm_adyen_notification.notification',
          'table_name' => 'civicrm_adyen_notification',
          'entity' => 'AdyenNotification',
          'bao' => 'CRM_Adyen_DAO_AdyenNotification',
          'localizable' => 0,
          'serialize' => self::SERIALIZE_JSON,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'adyen_notification', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'adyen_notification', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
